#!/bin/sh
CC=~/ellcc/ellcc/arm-elf-ecc
CFLAGS="-DHAVE_OPENDIR -I. -Iinclude"
#CC=gcc
#CFLAGS="-DHAVE_OPENDIR -nostdinc -I. -Iinclude"
for i in */*.c ; do
    echo $CC -c $CFLAGS $i
    $CC -c $CFLAGS $i
    if [ $? -ne 0 ] ; then
        echo echo compilation failed
        exit 1
    fi
done
