#include <ecc_test.h>
#include <tgmath.h>

TEST_GROUP(Tgmath)
#if RICH
    int i = 0;
    long l = 0;
    long long ll = 0;
    float f = 0;
    double d = 0;
    long double ld = 0;
    float complex fc = 0;
    double complex dc = 0;
    long double complex ldc = 0;
    TEST_TRACE(C99 7.22/4)
    f = acos(f);
    d = acos(d);
    TEST_UNSUPPORTED(ld = acos(ld);)
    fc = acos(fc);
    dc = acos(dc);
    TEST_UNSUPPORTED(ldc = acos(ldc);)
    f = asin(f);
    d = asin(d);
    TEST_UNSUPPORTED(ld = asin(ld);)
    fc = asin(fc);
    dc = asin(dc);
    TEST_UNSUPPORTED(ldc = asin(ldc);)
    f = atan(f);
    d = atan(d);
    TEST_UNSUPPORTED(ld = atan(ld);)
    fc = atan(fc);
    dc = atan(dc);
    TEST_UNSUPPORTED(ldc = atan(ldc);)
    f = acosh(f);
    d = acosh(d);
    TEST_UNSUPPORTED(ld = acosh(ld);)
    fc = acosh(fc);
    dc = acosh(dc);
    TEST_UNSUPPORTED(ldc = acosh(ldc);)
    f = asinh(f);
    d = asinh(d);
    TEST_UNSUPPORTED(ld = asinh(ld);)
    fc = asinh(fc);
    dc = asinh(dc);
    TEST_UNSUPPORTED(ldc = asinh(ldc);)
    f = atanh(f);
    d = atanh(d);
    TEST_UNSUPPORTED(ld = atanh(ld);)
    fc = atanh(fc);
    dc = atanh(dc);
    TEST_UNSUPPORTED(ldc = atanh(ldc);)
    f = cos(f);
    d = cos(d);
    TEST_UNSUPPORTED(ld = cos(ld);)
    fc = cos(fc);
    dc = cos(dc);
    TEST_UNSUPPORTED(ldc = cos(ldc);)
    f = asin(f);
    d = asin(d);
    TEST_UNSUPPORTED(ld = sin(ld);)
    fc = sin(fc);
    dc = sin(dc);
    TEST_UNSUPPORTED(ldc = sin(ldc);)
    f = atan(f);
    d = atan(d);
    TEST_UNSUPPORTED(ld = tan(ld);)
    fc = tan(fc);
    dc = tan(dc);
    TEST_UNSUPPORTED(ldc = tan(ldc);)
    f = cosh(f);
    d = cosh(d);
    TEST_UNSUPPORTED(ld = cosh(ld);)
    fc = cosh(fc);
    dc = cosh(dc);
    TEST_UNSUPPORTED(ldc = cosh(ldc);)
    f = sinh(f);
    d = sinh(d);
    TEST_UNSUPPORTED(ld = sinh(ld);)
    fc = sinh(fc);
    dc = sinh(dc);
    TEST_UNSUPPORTED(ldc = sinh(ldc);)
    f = tanh(f);
    d = tanh(d);
    TEST_UNSUPPORTED(ld = tanh(ld);)
    fc = tanh(fc);
    dc = tanh(dc);
    TEST_UNSUPPORTED(ldc = tanh(ldc);)
    f = exp(f);
    d = exp(d);
    TEST_UNSUPPORTED(ld = exp(ld);)
    fc = exp(fc);
    dc = exp(dc);
    TEST_UNSUPPORTED(ldc = exp(ldc);)
    f = log(f);
    d = log(d);
    TEST_UNSUPPORTED(ld = log(ld);)
    fc = log(fc);
    dc = log(dc);
    TEST_UNSUPPORTED(ldc = log(ldc);)
    f = pow(f, f);
    d = pow(d, d);
    TEST_UNSUPPORTED(ld = pow(ld, ld);)
    fc = pow(fc, fc);
    dc = pow(dc, dc);
    TEST_UNSUPPORTED(ldc = pow(ldc, ldc);)
    f = sqrt(f);
    d = sqrt(d);
    TEST_UNSUPPORTED(ld = sqrt(ld);)
    fc = sqrt(fc);
    dc = sqrt(dc);
    TEST_UNSUPPORTED(ldc = sqrt(ldc);)
    f = fabs(f);
    d = fabs(d);
    TEST_UNSUPPORTED(ld = fabs(ld);)
    fc = fabs(fc);
    dc = fabs(dc);
    TEST_UNSUPPORTED(ldc = fabs(ldc);)
    TEST_TRACE(C99 7.22/5)
    f = atan2(f, f);
    d = atan2(d, d);
    TEST_UNSUPPORTED(ld = atan2(ld, ld);)
    f = cbrt(f);
    d = cbrt(d);
    TEST_UNSUPPORTED(ld = cbrt(ld);)
    f = ceil(f);
    d = ceil(d);
    TEST_UNSUPPORTED(ld = ceil(ld);)
    f = copysign(f, f);
    d = copysign(d, d);
    ld = copysign(ld, ld);
    f = erf(f);
    d = erf(d);
    TEST_UNSUPPORTED(ld = erf(ld);)
    f = erfc(f);
    d = erfc(d);
    TEST_UNSUPPORTED(ld = erfc(ld);)
    f = exp2(f);
    d = exp2(d);
    TEST_UNSUPPORTED(ld = exp2(ld);)
    f = expm1(f);
    d = expm1(d);
    TEST_UNSUPPORTED(ld = expm1(ld);)
    f = fdim(f, f);
    d = fdim(d, d);
    TEST_UNSUPPORTED(ld = fdim(ld, ld);)
    f = floor(f);
    d = floor(d);
    TEST_UNSUPPORTED(ld = floor(ld);)
    TEST_UNSUPPORTED(f = fma(f);)
    TEST_UNSUPPORTED(d = fma(d);)
    TEST_UNSUPPORTED(ld = fma(ld);)
    f = fmax(f, f);
    d = fmax(d, d);
    TEST_UNSUPPORTED(ld = fmax(ld, ld);)
    f = fmin(f, f);
    d = fmin(d, d);
    TEST_UNSUPPORTED(ld = fmin(ld, ld);)
    f = fmod(f, f);
    d = fmod(d, d);
    TEST_UNSUPPORTED(ld = fmod(ld, ld);)
    f = frexp(f, &i);
    d = frexp(d, &i);
    TEST_UNSUPPORTED(ld = frexp(ld, &i);)
    f = hypot(f, f);
    d = hypot(d, d);
    TEST_UNSUPPORTED(ld = hypot(ld, ld);)
    f = ilogb(f);
    d = ilogb(d);
    TEST_UNSUPPORTED(ld = ilogb(ld);)
    f = ldexp(f, 1);
    d = ldexp(d, 1);
    TEST_UNSUPPORTED(ld = ldexp(ld, 1);)
    f = lgamma(f);
    d = lgamma(d);
    TEST_UNSUPPORTED(ld = lgamma(ld);)
    ll = llrint(f);
    ll = llrint(d);
    TEST_UNSUPPORTED(ll = llrint(ld);)
    ll = llround(f);
    ll = llround(d);
    TEST_UNSUPPORTED(ll = llround(ld);)
    f = log10(f);
    d = log10(d);
    TEST_UNSUPPORTED(ld = log10(ld);)
    f = log1p(f);
    d = log1p(d);
    TEST_UNSUPPORTED(ld = log1p(ld);)
    f = log2(f);
    d = log2(d);
    TEST_UNSUPPORTED(ld = log2(ld);)
    f = logb(f);
    d = logb(d);
    TEST_UNSUPPORTED(ld = logb(ld);)
    l = lrint(f);
    l = lrint(d);
    TEST_UNSUPPORTED(l = lrint(ld);)
    l = lround(f);
    l = lround(d);
    TEST_UNSUPPORTED(l = lround(ld);)
    f = nearbyint(f);
    d = nearbyint(d);
    TEST_UNSUPPORTED(ld = nearbyint(ld);)
    f = nextafter(f, f);
    d = nextafter(d, d);
    TEST_EXCLUDE(PPC, "http://ellcc.org/bugzilla/show_bug.cgi?id=47")
    TEST_EXCLUDE(PPC64, "http://ellcc.org/bugzilla/show_bug.cgi?id=47")
        ld = nextafter(ld, ld);
    TEST_UNSUPPORTED(f = nexttoward(f, f);)
    TEST_UNSUPPORTED(d = nexttoward(d, d);)
    TEST_UNSUPPORTED(ld = nexttoward(ld, ld);)
    f = remainder(f, f);
    d = remainder(d, d);
    TEST_UNSUPPORTED(ld = remainder(ld, ld);)
    TEST_UNSUPPORTED(f = remquo(f, f, &i);)
    TEST_UNSUPPORTED(d = remquo(d, d, &i);)
    TEST_UNSUPPORTED(ld = remquo(ld, ld, &i);)
    f = rint(f);
    d = rint(d);
    TEST_UNSUPPORTED(ld = rint(ld);)
    f = round(f);
    d = round(d);
    TEST_UNSUPPORTED(ld = round(ld);)
    f = scalbn(f, 1);
    d = scalbn(d, 1);
    TEST_UNSUPPORTED(ld = scalbn(ld, 1);)
    f = scalbln(f, 1);
    d = scalbln(d, 1);
    TEST_UNSUPPORTED(ld = scalbln(ld, 1);)
    f = tgamma(f);
    d = tgamma(d);
    TEST_UNSUPPORTED(ld = tgamma(ld);)
    f = trunc(f);
    d = trunc(d);
    TEST_UNSUPPORTED(ld = trunc(ld);)
    TEST_TRACE(C99 7.22/6)
    fc = carg(fc);
    dc = carg(dc);
    TEST_UNSUPPORTED(ldc = carg(ldc);)
    fc = cimag(fc);
    dc = cimag(dc);
    TEST_UNSUPPORTED(ldc = cimag(ldc);)
    fc = conj(fc);
    dc = conj(dc);
    TEST_UNSUPPORTED(ldc = conj(ldc);)
    fc = cproj(fc);
    dc = cproj(dc);
    TEST_UNSUPPORTED(ldc = cproj(ldc);)
    f = creal(fc);
    d = creal(dc);
    TEST_UNSUPPORTED(ld = creal(ldc);)
#endif
END_GROUP
