SCRIPT_NAME=elf
OUTPUT_FORMAT="elf32-littlenios2"
LITTLE_OUTPUT_FORMAT="elf32-littlenios2"
BIG_OUTPUT_FORMAT="elf32-bignios2"
TEXT_START_ADDR=0x0
OTHER_GOT_SYMBOLS='
  _gp = ALIGN(16) + 0x7ff0;
  PROVIDE(gp = _gp);
'
ARCH=nios2
MACHINE=
MAXPAGESIZE=256
ENTRY=_start
EMBEDDED=yes
DATA_ADDR=.
NOP=0x0001883a

