#!/bin/sh
CC=~/ellcc/ellcc/$1-elf-ecc
CFLAGS="-DHAVE_OPENDIR -I. -I../soft-int"
#CC=gcc
#CFLAGS="-DHAVE_OPENDIR -nostdinc -I. -I../soft-int"
for i in *.c ; do
    echo $CC -c $CFLAGS $i
    $CC -c $CFLAGS $i
    if [ $? -ne 0 ] ; then
        echo compilation failed
        exit 1
    fi
done
