TARGET := ppc
Arch.$(TARGET) := ppc
TARGET.$(TARGET) := -target $(TARGET)-ellcc-$(OS)
CFLAGS.$(TARGET) := $(TARGET.$(TARGET)) $(CFLAGS)
CXXFLAGS.$(TARGET) := $(TARGET.$(TARGET)) $(CXXFLAGS)
LDFLAGS := $(TARGET.$(TARGET))
