#!/bin/sh

prefix=/home/rich/local
targets=`cat ../targets`
targetlist=`echo $targets | sed -e "s/ /,/g"`
ellcc=`cd ../ellcc; pwd`
#cc=$ellcc/ecc
#cxx=$ellcc/e++
cc=gcc
cxx=g++


# Parse options.
install=0
while [ $# -gt 0 ] ; do
  case $1 in
    install)
      install=1 ;;
    *)
      echo "illegal option '$1'"
      exit ;;
  esac
  shift
done

if [ $install -eq 0 ] ; then
  rm -fr obj
  mkdir obj
fi

cd obj

if [ $install -eq 0 ] ; then
  echo Making binutils for $targets
  ../src/configure CC=$cc CXX=$cxx --enable-64-bit-bfd --enable-targets=$targetlist --program-prefix=ecc- --prefix=$prefix
  if [ $? -ne 0 ] ; then
    echo configure for binutils failed
    exit 1
  fi

  sed -e "s:/.*/gnu/src/missing ::g" Makefile > tmp$$
  mv tmp$$ Makefile

  make
  if [ $? -ne 0 ] ; then
    echo make for binutils failed
    exit 1
  fi
else
  make install
  if [ $? -ne 0 ] ; then
    echo make install for binutils failed
    exit 1
  fi
fi

cd ..

cd obj
for t in $targets; do
  if [ $install -eq 0 ] ; then
    mkdir $t
    cd $t
    echo Making the assembler for $t
    ../../src/gas/configure CC=$cc CXX=$cxx --target=$t --program-prefix=${t}- --prefix=$prefix
    if [ $? -ne 0 ] ; then
      echo configure for $t failed
      exit 1
    fi
    make
    if [ $? -ne 0 ] ; then
      echo make for $t failed
      exit 1
    fi
  else
    cd $t
    make install
    if [ $? -ne 0 ] ; then
      echo make install for $t failed
      exit 1
    fi
  fi
  cd ..
done
cd ..
